minimumBalance.new=1000.0
minimumBalance.standard=1000.0
minimumBalance.premium=1000.0
overdraft.limit.new=25000.0
overdraft.limit.standard=25000.0
overdraft.limit.premium=25000.0
dailyTransferLimit.new=100000.0
dailyTransferLimit.standard=500000.0
dailyTransferLimit.premium=1000000.0
