minimumBalance.new=0.0
minimumBalance.standard=0.0
minimumBalance.premium=0.0
minimumBalance.privilege=0.0
interestRate.new=5.5
interestRate.standard=6.0
interestRate.premium=6.5
interestRate.privilege=6.5
dailyTransferLimit.new=0.0
dailyTransferLimit.standard=0.0
dailyTransferLimit.premium=0.0
dailyTransferLimit.privilege=0.0
