minimumBalance.new=0.0
minimumBalance.standard=0.0
minimumBalance.premium=0.0
minimumBalance.privilege=0.0
dailyTransferLimit.new=100000.0
dailyTransferLimit.standard=500000.0
dailyTransferLimit.premium=1000000.0
dailyTransferLimit.privilege=2500000.0
