minimumBalance.new=10000.0
minimumBalance.standard=7500.0
minimumBalance.premium=5000.0
minimumBalance.privilege=2500.0
interestRate.new=2.70
interestRate.standard=3.00
interestRate.premium=3.50
interestRate.privilege=4.00
dailyTransferLimit.new=50000.0
dailyTransferLimit.standard=100000.0
dailyTransferLimit.premium=200000.0
dailyTransferLimit.privilege=500000.0
